### ISSUE TITLE
race on startedTypes

### ISSUE THREAD

**Issue by sbinet** [driusan/dainit#1]
you probably have a data race on startedTypes:
https://github.com/driusan/dainit/blob/master/service.go#L53
which is populated (and read) by many goroutines concurrently.

**Comment by driusan** [comment]
Is there something wrong with the logic in this comment about why it's harmless?

https://github.com/driusan/dainit/blob/master/service.go#L73

If there's multiple writers, they're both setting to the same thing. If a reader wins the race, it'll just wait 2 seconds before trying again.

**Comment by sbinet** [comment]
well, ok.
but IIRC, concurrent (write) map access may confuse the GC (or leave the map in a funny state).

**Comment by driusan** [comment]
I suppose it wouldn't hurt to use a sync.RWMutex. I'll get to that as soon as I finish adding code to reap zombie processes.
